services:
  etcd:
    container_name: milvus-etcd-roles
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd-cze:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    container_name: milvus-minio-roles
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio-cze:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone-roles
    image: milvusdb/milvus:v2.4.13-gpu
    command: ["milvus", "run", "standalone"]
    security_opt:
      - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus-cze:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]
              device_ids: ["0"]
    depends_on:
      etcd:
        condition: service_healthy
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:19530/healthz"]
      interval: 30s
      timeout: 20s
      retries: 5

  neo4j:
    container_name: neo4j-roles
    image: neo4j:5.5
    environment:
      NEO4J_AUTH: neo4j/testtest
    ports:
      - "7687:7687"
      - "7474:7474"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/neo4j-cze:/data
    depends_on:
      - standalone

  db:
    image: postgres:15
    container_name: postgres-roles
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_DB: chatdb
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 30s
      timeout: 20s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:8.13.0
    container_name: pgadmin-roles
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminadmin
    ports:
      - "5050:80"
    depends_on:
      - db

  attu:
    container_name: milvus-attu
    image: zilliz/attu:v2.4.11
    environment:
      MILVUS_URL: standalone:19530
    ports:
      - "8800:3000"
    depends_on:
      - standalone

  resolvei:
    container_name: resolvei-retrieval-server
    image: ghcr.io/marekruttner/resolvei-retrieval-server:resolvei-latest
    environment:
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=adminadmin
      - NEO4J_URI=neo4j://neo4j-roles:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=testtest
    ports:
      - "8000:8000"
    depends_on:
      - db
      - standalone
      - neo4j

  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ "gpu" ]
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped

  ################################################################
  # New Tailscale service for VPN
  ################################################################
  tailscale:
    container_name: tailscale
    image: tailscale/tailscale:stable
    # We'll use the host network so that you can reach all
    # exposed ports via your host's Tailscale IP.
    network_mode: host
    privileged: true
    volumes:
      - tailscale-data:/var/lib/tailscale
    environment:
      # Provide your Tailscale auth key here, e.g.:
      # TS_AUTHKEY=tskey-abc123...
      - TS_AUTHKEY=tskey-auth-k3A2ottBSW11CNTRL-bbZtpGnFpaFUjcaoVC9DbFWaSniEytubf
    # We'll run tailscaled in the background, then "tailscale up".
    command: >
      sh -c "
        tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/var/run/tailscale/tailscaled.sock &
        # Wait a moment for tailscaled to start
        sleep 3
        tailscale up --accept-routes --hostname='resolvei-docker' --authkey=${TS_AUTHKEY}
        # Keep container running
        tail -f /dev/null
      "

volumes:
  tailscale-data:
  ollama-data:
