name: Build & Push Resolvei Docker Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

###############################################
# Add permissions to allow pushing to GHCR
###############################################
permissions:
  contents: read     # read code
  packages: write    # crucial for pushing to GHCR

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the code
      - name: Check out code
        uses: actions/checkout@v3

      # 2) (Optional) Set up QEMU (needed if building multi-platform images)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 3) (Optional) Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4) Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 5) Build and push the Docker image
      - name: Build and push Resolvei image
        uses: docker/build-push-action@v4
        with:
          # Adjust context if Dockerfile is in a subfolder
          context: .
          # If Dockerfile is not named "Dockerfile", specify:
          #   dockerfile: <path/to/yourDockerfile>

          platforms: linux/amd64
          push: true

          tags: |
            ghcr.io/${{ github.repository }}:resolvei-latest

